#ifndef __SPS__GOOD_GAME__EXTEND_FREE_TYPE_HELPER_BASE__FTH_CONFIG_H__
#define __SPS__GOOD_GAME__EXTEND_FREE_TYPE_HELPER_BASE__FTH_CONFIG_H__



#define __GG__FTH__MAKE_DEBUG				0



#endif // #ifndef __SPS__GOOD_GAME__EXTEND_FREE_TYPE_HELPER_BASE__FTH_CONFIG_H__
